AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'node_modules/**/*'
  ExtraDetails: true
  TargetRubyVersion: 2.5

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
